[package]
name = "iroh-rpc-client"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type client for iroh"

[dependencies]
async-stream = "0.3.0"
iroh-util = { path = "../iroh-util" }
iroh-rpc-types = { path = "../iroh-rpc-types", features = ["testing"] }
cid = "0.8.0"
futures = "0.3.21"
tokio = { version = "1.0", features = ["sync"] }
tonic = "0.7.2"
tonic-health = "0.6.0"
prost = "0.10.3"
anyhow = "1.0.57"
bytes = "1.1.0"
libp2p = { version = "0.46", features=["gossipsub"], default-features = false }
iroh-metrics = { path = "../iroh-metrics" }
tracing = "0.1.34"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
config = "0.13.1"

[dev-dependencies]
tokio-stream = { version = "0.1.9", features = ["net"]}
