[package]
name = "iroh-resolver"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of path resolution for iroh"

[dependencies]
anyhow = "1"
cid = "0.8.4"
libipld = "0.13.1"
num_enum = "0.5.7"
prost = "0.10"
bytes = "1.1.0"
iroh-rpc-client = { path = "../iroh-rpc-client" }
tokio = { version = "1.18.0" }
futures = "0.3.5"
tracing = "0.1.34"
async-trait = "0.1.53"
async-recursion = "1.0.0"
trust-dns-resolver = { version = "0.21.2", features = ["tokio-runtime"] }
prometheus-client = "0.16.0"
iroh-metrics = { path = "../iroh-metrics" }
async-stream = "0.3.3"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
tempfile = "3.3.0"
tokio = { version = "1.18.0", features = ["rt", "macros", "rt-multi-thread"] }

[build-dependencies]
prost-build = "0.10"

[features]
default = []

